apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: question4
spec:
  volumes:
  - name: vol
    emptyDir: {}
  containers:
  - name: c1
    image: busybox:1.31.1
    command:
    - /bin/sh
    - -c
    - |
      while true; do
        date >> /vol/date.log
        sleep 5
      done
    volumeMounts:
    - name: vol
      mountPath: /vol
  - name: c2
    image: busybox:1.31.1
    command:
    - /bin/sh
    - -c
    - tail -f /vol/date.log
    volumeMounts:
    - name: vol
      mountPath: /vol
